FROM nvcr.io/nvidia/pytorch:24.06-py3

COPY requirements.txt /tmp/requirements.txt

# Add grant sudo to host users that have sudo or docker.
RUN apt-get update && apt-get install -y sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    echo "%docker ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    echo "%sudo ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN pip install -r /tmp/requirements.txt && \
    rm -Rf /root/.cache/pip